<%@ Page Title="" Language="C#" MasterPageFile="~/Director.Master" AutoEventWireup="true" CodeBehind="MasterItem.aspx.cs" Inherits="EngMgr.MasterItem" %>
<%@ Register assembly="Microsoft.ReportViewer.WebForms, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" namespace="Microsoft.Reporting.WebForms" tagprefix="rsweb" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <rsweb:ReportViewer ID="ReportViewer1" runat="server" Font-Names="Verdana" Font-Size="8pt" WaitMessageFont-Names="Verdana" WaitMessageFont-Size="14pt" Width="100%">
        <LocalReport ReportPath="MasterItems.rdlc">
            <DataSources>
                <rsweb:ReportDataSource DataSourceId="ObjectDataSource1" Name="DataSet1" />
            </DataSources>
        </LocalReport>
    </rsweb:ReportViewer>
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" DeleteMethod="Delete" InsertMethod="Insert" OldValuesParameterFormatString="original_{0}" SelectMethod="GetData" TypeName="EngMgr.MasterDataSetTableAdapters.JobEngineTableAdapter" UpdateMethod="Update">
        <DeleteParameters>
            <asp:Parameter Name="Original_ID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="POnumber" Type="String" />
            <asp:Parameter Name="COnumber" Type="String" />
            <asp:Parameter Name="ShipDate" Type="DateTime" />
            <asp:Parameter Name="Notes" Type="String" />
            <asp:Parameter Name="DateRecvd" Type="DateTime" />
            <asp:Parameter Name="Company" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Phone" Type="String" />
            <asp:Parameter Name="POC" Type="String" />
            <asp:Parameter Name="Status" Type="String" />
            <asp:Parameter Name="GAdwg" Type="String" />
            <asp:Parameter Name="GArev" Type="String" />
            <asp:Parameter Name="Dwg1" Type="String" />
            <asp:Parameter Name="Dwg2" Type="String" />
            <asp:Parameter Name="Dwg3" Type="String" />
            <asp:Parameter Name="Dwg4" Type="String" />
            <asp:Parameter Name="Dwg5" Type="String" />
            <asp:Parameter Name="Dwg6" Type="String" />
            <asp:Parameter Name="Dwg7" Type="String" />
            <asp:Parameter Name="Dwg8" Type="String" />
            <asp:Parameter Name="Dwg9" Type="String" />
            <asp:Parameter Name="Dwg10" Type="String" />
            <asp:Parameter Name="Dwg11" Type="String" />
            <asp:Parameter Name="Dwg12" Type="String" />
            <asp:Parameter Name="Dwgdatecomp1" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp2" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp3" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp4" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp5" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp6" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp7" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp8" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp9" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp10" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp11" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp12" Type="DateTime" />
            <asp:Parameter Name="ItemQty" Type="Decimal" />
            <asp:Parameter Name="Item" Type="String" />
            <asp:Parameter Name="AssnTo" Type="String" />
            <asp:Parameter Name="GAReqdDate" Type="DateTime" />
            <asp:Parameter Name="GACompDate" Type="DateTime" />
            <asp:Parameter Name="GAtoSalesDate" Type="DateTime" />
            <asp:Parameter Name="GAtoCustDate" Type="DateTime" />
            <asp:Parameter Name="FirstAppDate" Type="DateTime" />
            <asp:Parameter Name="TAdwgnum" Type="String" />
            <asp:Parameter Name="TACompDAte" Type="DateTime" />
            <asp:Parameter Name="TABOMEntereddate" Type="DateTime" />
            <asp:Parameter Name="TARELtoPlanDate" Type="DateTime" />
            <asp:Parameter Name="ELdwgnum" Type="String" />
            <asp:Parameter Name="ELCompDate" Type="DateTime" />
            <asp:Parameter Name="ELBOMentereddate" Type="DateTime" />
            <asp:Parameter Name="ELRELtoPlanDate" Type="DateTime" />
            <asp:Parameter Name="HYdwgnum" Type="String" />
            <asp:Parameter Name="HYcompDate" Type="DateTime" />
            <asp:Parameter Name="HYbomentereddate" Type="DateTime" />
            <asp:Parameter Name="HYRELtoplandate" Type="DateTime" />
            <asp:Parameter Name="PNdwgnum" Type="String" />
            <asp:Parameter Name="PNcompdate" Type="DateTime" />
            <asp:Parameter Name="PNBOMentereddate" Type="DateTime" />
            <asp:Parameter Name="PNRELtoplan" Type="DateTime" />
            <asp:Parameter Name="Reqdcustmanual" Type="Boolean" />
            <asp:Parameter Name="PrevCOnum" Type="Int32" />
            <asp:Parameter Name="SYSPROPdwgnum" Type="String" />
            <asp:Parameter Name="SYSPROPcompdate" Type="DateTime" />
            <asp:Parameter Name="SYSPROPtosalesdate" Type="DateTime" />
            <asp:Parameter Name="INSTALLdwgnum" Type="String" />
            <asp:Parameter Name="INSTALLcompdate" Type="DateTime" />
            <asp:Parameter Name="INSTALLtosalesdate" Type="DateTime" />
            <asp:Parameter Name="Seizmicin" Type="DateTime" />
            <asp:Parameter Name="Seizmicout" Type="DateTime" />
            <asp:Parameter Name="SN" Type="String" />
            <asp:Parameter Name="Salesdwgref" Type="String" />
            <asp:Parameter Name="TARELFROMplan" Type="DateTime" />
            <asp:Parameter Name="HYRELFROMplan" Type="DateTime" />
            <asp:Parameter Name="ELRELFROMplan" Type="DateTime" />
            <asp:Parameter Name="PNRELFROMplan" Type="DateTime" />
            <asp:Parameter Name="ShippedWithEquipment" Type="Boolean" />
            <asp:Parameter Name="Mailedtocustomer" Type="Boolean" />
            <asp:Parameter Name="twocdsmailedtocustomer" Type="Boolean" />
            <asp:Parameter Name="mancompdate" Type="DateTime" />
            <asp:Parameter Name="manualmaileddate" Type="DateTime" />
            <asp:Parameter Name="cdsmaileddate" Type="DateTime" />
            <asp:Parameter Name="SVCmanualcompdate" Type="DateTime" />
            <asp:Parameter Name="SVCmansenttosvcdept" Type="DateTime" />
            <asp:Parameter Name="ManualComments" Type="String" />
            <asp:Parameter Name="ItemDESCRIPTION" Type="String" />
            <asp:Parameter Name="refSN" Type="String" />
            <asp:Parameter Name="refJOBnum" Type="String" />
            <asp:Parameter Name="dwnby1" Type="String" />
            <asp:Parameter Name="dwnby2" Type="String" />
            <asp:Parameter Name="dwnby3" Type="String" />
            <asp:Parameter Name="dwnby4" Type="String" />
            <asp:Parameter Name="dwnby5" Type="String" />
            <asp:Parameter Name="dwnby6" Type="String" />
            <asp:Parameter Name="dwnby7" Type="String" />
            <asp:Parameter Name="dwnby8" Type="String" />
            <asp:Parameter Name="dwnby9" Type="String" />
            <asp:Parameter Name="dwnby10" Type="String" />
            <asp:Parameter Name="dwnby11" Type="String" />
            <asp:Parameter Name="dwnby12" Type="String" />
            <asp:Parameter Name="BOMentereddate1" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN1" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN1" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate2" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN2" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN2" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate3" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN3" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN3" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate4" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN4" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN4" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate5" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN5" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN5" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate6" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN6" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN6" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate7" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN7" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN7" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate8" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN8" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN8" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate9" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN9" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN9" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate10" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN10" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN10" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate11" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN11" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN11" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate12" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN12" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN12" Type="DateTime" />
            <asp:Parameter Name="RushBlock" Type="String" />
            <asp:Parameter Name="email" Type="String" />
            <asp:Parameter Name="BOMENTEREDTA" Type="String" />
            <asp:Parameter Name="BOMENTEREDEL" Type="String" />
            <asp:Parameter Name="BOMENTEREDHY" Type="String" />
            <asp:Parameter Name="BOMENTEREDPN" Type="String" />
            <asp:Parameter Name="GAdwnby" Type="String" />
            <asp:Parameter Name="GAREVdate2" Type="DateTime" />
            <asp:Parameter Name="GAREVdate3" Type="DateTime" />
            <asp:Parameter Name="GAREVdate4" Type="DateTime" />
            <asp:Parameter Name="GAREVdate1" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES1" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES2" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES3" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES4" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST1" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST2" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST3" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST4" Type="DateTime" />
            <asp:Parameter Name="StockConfirmedby" Type="String" />
            <asp:Parameter Name="SotckConfirmedbydate" Type="DateTime" />
            <asp:Parameter Name="CurrentStatus" Type="String" />
            <asp:Parameter Name="PrimaryVoltage" Type="String" />
            <asp:Parameter Name="JOnum" Type="String" />
            <asp:Parameter Name="Quoterefnum" Type="String" />
            <asp:Parameter Name="TONP" Type="DateTime" />
            <asp:Parameter Name="ECNREV1" Type="String" />
            <asp:Parameter Name="ECNREV2" Type="String" />
            <asp:Parameter Name="ECNREV3" Type="String" />
            <asp:Parameter Name="ECNREV4" Type="String" />
            <asp:Parameter Name="HPU" Type="String" />
            <asp:Parameter Name="Vahle" Type="String" />
            <asp:Parameter Name="GAREVdate5" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST5" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES5" Type="DateTime" />
            <asp:Parameter Name="ECNREV5" Type="String" />
            <asp:Parameter Name="OSD" Type="DateTime" />
            <asp:Parameter Name="MultiECN" Type="String" />
            <asp:Parameter Name="MultiECNDate" Type="DateTime" />
            <asp:Parameter Name="RA" Type="Boolean" />
            <asp:Parameter Name="TL" Type="Boolean" />
            <asp:Parameter Name="RG" Type="Boolean" />
            <asp:Parameter Name="LT" Type="Boolean" />
            <asp:Parameter Name="BR" Type="Boolean" />
            <asp:Parameter Name="JW" Type="Boolean" />
            <asp:Parameter Name="BW" Type="Boolean" />
            <asp:Parameter Name="HC" Type="Boolean" />
            <asp:Parameter Name="JR" Type="Boolean" />
            <asp:Parameter Name="LW" Type="Boolean" />
            <asp:Parameter Name="RC" Type="Boolean" />
            <asp:Parameter Name="JT" Type="Boolean" />
            <asp:Parameter Name="ECN1" Type="String" />
            <asp:Parameter Name="ECN2" Type="String" />
            <asp:Parameter Name="ECN3" Type="String" />
            <asp:Parameter Name="ECN4" Type="String" />
            <asp:Parameter Name="ECN5" Type="String" />
            <asp:Parameter Name="ECN6" Type="String" />
            <asp:Parameter Name="ECNDate1" Type="DateTime" />
            <asp:Parameter Name="ECNDate2" Type="DateTime" />
            <asp:Parameter Name="ECNDate3" Type="DateTime" />
            <asp:Parameter Name="ECNDate4" Type="DateTime" />
            <asp:Parameter Name="ECNDate5" Type="DateTime" />
            <asp:Parameter Name="ECNDate6" Type="DateTime" />
            <asp:Parameter Name="ECN1Text" Type="String" />
            <asp:Parameter Name="ECN2Text" Type="String" />
            <asp:Parameter Name="ECN3Text" Type="String" />
            <asp:Parameter Name="ECN4Text" Type="String" />
            <asp:Parameter Name="ECN5Text" Type="String" />
            <asp:Parameter Name="ECN6Text" Type="String" />
            <asp:Parameter Name="GAESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="ELESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="TAESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="ELREQD" Type="Boolean" />
            <asp:Parameter Name="OrdernotesESR" Type="String" />
            <asp:Parameter Name="SYSPROPESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="HYESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="PNESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="INSTALLESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="SOnum" Type="String" />
            <asp:Parameter Name="RW" Type="Boolean" />
            <asp:Parameter Name="LabelType" Type="String" />
            <asp:Parameter Name="LabelDateComp" Type="DateTime" />
            <asp:Parameter Name="LabelDateSent" Type="DateTime" />
            <asp:Parameter Name="LabelMethod" Type="String" />
            <asp:Parameter Name="LabelRecvd" Type="DateTime" />
            <asp:Parameter Name="LabelRecvdBy" Type="String" />
            <asp:Parameter Name="ECNDate7" Type="String" />
            <asp:Parameter Name="ECN7" Type="String" />
            <asp:Parameter Name="ECN7Text" Type="String" />
            <asp:Parameter Name="ECNDate8" Type="String" />
            <asp:Parameter Name="ECN8" Type="String" />
            <asp:Parameter Name="ECN8Text" Type="String" />
            <asp:Parameter Name="Drafter7" Type="String" />
            <asp:Parameter Name="lead_setter" Type="String" />
            <asp:Parameter Name="WW" Type="Boolean" />
            <asp:Parameter Name="manMOD" Type="String" />
            <asp:Parameter Name="Date_to_Check" Type="DateTime" />
            <asp:Parameter Name="Job_Date_Check_Complete" Type="DateTime" />
            <asp:Parameter Name="Job_Date_to_BOM" Type="DateTime" />
            <asp:Parameter Name="Job_Date_Rel_To_Plan" Type="DateTime" />
            <asp:Parameter Name="control_est_rel_date" Type="DateTime" />
            <asp:Parameter Name="control_comp_date" Type="DateTime" />
            <asp:Parameter Name="control_to_plan_date" Type="DateTime" />
            <asp:Parameter Name="Item_category" Type="String" />
            <asp:Parameter Name="LeadTime" Type="String" />
            <asp:Parameter Name="ECNDate9" Type="String" />
            <asp:Parameter Name="ECN9" Type="String" />
            <asp:Parameter Name="ECN9Text" Type="String" />
            <asp:Parameter Name="ECNDate10" Type="String" />
            <asp:Parameter Name="ECN10" Type="String" />
            <asp:Parameter Name="ECN10Text" Type="String" />
            <asp:Parameter Name="ECNDate11" Type="String" />
            <asp:Parameter Name="ECN11" Type="String" />
            <asp:Parameter Name="ECN11Text" Type="String" />
            <asp:Parameter Name="ECNDate12" Type="String" />
            <asp:Parameter Name="ECN12" Type="String" />
            <asp:Parameter Name="ECN12Text" Type="String" />
            <asp:Parameter Name="Labels_Reqd" Type="Boolean" />
            <asp:Parameter DbType="Time" Name="TimeCreated" />
            <asp:Parameter Name="DateCreated" Type="DateTime" />
            <asp:Parameter Name="Label_ID" Type="Int32" />
            <asp:Parameter Name="Date_Modified" Type="DateTime" />
            <asp:Parameter Name="MECHNotes" Type="String" />
            <asp:Parameter Name="CONTROLNotes" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="POnumber" Type="String" />
            <asp:Parameter Name="COnumber" Type="String" />
            <asp:Parameter Name="ShipDate" Type="DateTime" />
            <asp:Parameter Name="Notes" Type="String" />
            <asp:Parameter Name="DateRecvd" Type="DateTime" />
            <asp:Parameter Name="Company" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Phone" Type="String" />
            <asp:Parameter Name="POC" Type="String" />
            <asp:Parameter Name="Status" Type="String" />
            <asp:Parameter Name="GAdwg" Type="String" />
            <asp:Parameter Name="GArev" Type="String" />
            <asp:Parameter Name="Dwg1" Type="String" />
            <asp:Parameter Name="Dwg2" Type="String" />
            <asp:Parameter Name="Dwg3" Type="String" />
            <asp:Parameter Name="Dwg4" Type="String" />
            <asp:Parameter Name="Dwg5" Type="String" />
            <asp:Parameter Name="Dwg6" Type="String" />
            <asp:Parameter Name="Dwg7" Type="String" />
            <asp:Parameter Name="Dwg8" Type="String" />
            <asp:Parameter Name="Dwg9" Type="String" />
            <asp:Parameter Name="Dwg10" Type="String" />
            <asp:Parameter Name="Dwg11" Type="String" />
            <asp:Parameter Name="Dwg12" Type="String" />
            <asp:Parameter Name="Dwgdatecomp1" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp2" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp3" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp4" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp5" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp6" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp7" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp8" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp9" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp10" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp11" Type="DateTime" />
            <asp:Parameter Name="Dwgdatecomp12" Type="DateTime" />
            <asp:Parameter Name="ItemQty" Type="Decimal" />
            <asp:Parameter Name="Item" Type="String" />
            <asp:Parameter Name="AssnTo" Type="String" />
            <asp:Parameter Name="GAReqdDate" Type="DateTime" />
            <asp:Parameter Name="GACompDate" Type="DateTime" />
            <asp:Parameter Name="GAtoSalesDate" Type="DateTime" />
            <asp:Parameter Name="GAtoCustDate" Type="DateTime" />
            <asp:Parameter Name="FirstAppDate" Type="DateTime" />
            <asp:Parameter Name="TAdwgnum" Type="String" />
            <asp:Parameter Name="TACompDAte" Type="DateTime" />
            <asp:Parameter Name="TABOMEntereddate" Type="DateTime" />
            <asp:Parameter Name="TARELtoPlanDate" Type="DateTime" />
            <asp:Parameter Name="ELdwgnum" Type="String" />
            <asp:Parameter Name="ELCompDate" Type="DateTime" />
            <asp:Parameter Name="ELBOMentereddate" Type="DateTime" />
            <asp:Parameter Name="ELRELtoPlanDate" Type="DateTime" />
            <asp:Parameter Name="HYdwgnum" Type="String" />
            <asp:Parameter Name="HYcompDate" Type="DateTime" />
            <asp:Parameter Name="HYbomentereddate" Type="DateTime" />
            <asp:Parameter Name="HYRELtoplandate" Type="DateTime" />
            <asp:Parameter Name="PNdwgnum" Type="String" />
            <asp:Parameter Name="PNcompdate" Type="DateTime" />
            <asp:Parameter Name="PNBOMentereddate" Type="DateTime" />
            <asp:Parameter Name="PNRELtoplan" Type="DateTime" />
            <asp:Parameter Name="Reqdcustmanual" Type="Boolean" />
            <asp:Parameter Name="PrevCOnum" Type="Int32" />
            <asp:Parameter Name="SYSPROPdwgnum" Type="String" />
            <asp:Parameter Name="SYSPROPcompdate" Type="DateTime" />
            <asp:Parameter Name="SYSPROPtosalesdate" Type="DateTime" />
            <asp:Parameter Name="INSTALLdwgnum" Type="String" />
            <asp:Parameter Name="INSTALLcompdate" Type="DateTime" />
            <asp:Parameter Name="INSTALLtosalesdate" Type="DateTime" />
            <asp:Parameter Name="Seizmicin" Type="DateTime" />
            <asp:Parameter Name="Seizmicout" Type="DateTime" />
            <asp:Parameter Name="SN" Type="String" />
            <asp:Parameter Name="Salesdwgref" Type="String" />
            <asp:Parameter Name="TARELFROMplan" Type="DateTime" />
            <asp:Parameter Name="HYRELFROMplan" Type="DateTime" />
            <asp:Parameter Name="ELRELFROMplan" Type="DateTime" />
            <asp:Parameter Name="PNRELFROMplan" Type="DateTime" />
            <asp:Parameter Name="ShippedWithEquipment" Type="Boolean" />
            <asp:Parameter Name="Mailedtocustomer" Type="Boolean" />
            <asp:Parameter Name="twocdsmailedtocustomer" Type="Boolean" />
            <asp:Parameter Name="mancompdate" Type="DateTime" />
            <asp:Parameter Name="manualmaileddate" Type="DateTime" />
            <asp:Parameter Name="cdsmaileddate" Type="DateTime" />
            <asp:Parameter Name="SVCmanualcompdate" Type="DateTime" />
            <asp:Parameter Name="SVCmansenttosvcdept" Type="DateTime" />
            <asp:Parameter Name="ManualComments" Type="String" />
            <asp:Parameter Name="ItemDESCRIPTION" Type="String" />
            <asp:Parameter Name="refSN" Type="String" />
            <asp:Parameter Name="refJOBnum" Type="String" />
            <asp:Parameter Name="dwnby1" Type="String" />
            <asp:Parameter Name="dwnby2" Type="String" />
            <asp:Parameter Name="dwnby3" Type="String" />
            <asp:Parameter Name="dwnby4" Type="String" />
            <asp:Parameter Name="dwnby5" Type="String" />
            <asp:Parameter Name="dwnby6" Type="String" />
            <asp:Parameter Name="dwnby7" Type="String" />
            <asp:Parameter Name="dwnby8" Type="String" />
            <asp:Parameter Name="dwnby9" Type="String" />
            <asp:Parameter Name="dwnby10" Type="String" />
            <asp:Parameter Name="dwnby11" Type="String" />
            <asp:Parameter Name="dwnby12" Type="String" />
            <asp:Parameter Name="BOMentereddate1" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN1" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN1" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate2" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN2" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN2" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate3" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN3" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN3" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate4" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN4" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN4" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate5" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN5" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN5" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate6" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN6" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN6" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate7" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN7" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN7" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate8" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN8" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN8" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate9" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN9" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN9" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate10" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN10" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN10" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate11" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN11" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN11" Type="DateTime" />
            <asp:Parameter Name="BOMentereddate12" Type="DateTime" />
            <asp:Parameter Name="DwgrelTOPLAN12" Type="DateTime" />
            <asp:Parameter Name="DwgrelFROMPLAN12" Type="DateTime" />
            <asp:Parameter Name="RushBlock" Type="String" />
            <asp:Parameter Name="email" Type="String" />
            <asp:Parameter Name="BOMENTEREDTA" Type="String" />
            <asp:Parameter Name="BOMENTEREDEL" Type="String" />
            <asp:Parameter Name="BOMENTEREDHY" Type="String" />
            <asp:Parameter Name="BOMENTEREDPN" Type="String" />
            <asp:Parameter Name="GAdwnby" Type="String" />
            <asp:Parameter Name="GAREVdate2" Type="DateTime" />
            <asp:Parameter Name="GAREVdate3" Type="DateTime" />
            <asp:Parameter Name="GAREVdate4" Type="DateTime" />
            <asp:Parameter Name="GAREVdate1" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES1" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES2" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES3" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES4" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST1" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST2" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST3" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST4" Type="DateTime" />
            <asp:Parameter Name="StockConfirmedby" Type="String" />
            <asp:Parameter Name="SotckConfirmedbydate" Type="DateTime" />
            <asp:Parameter Name="CurrentStatus" Type="String" />
            <asp:Parameter Name="PrimaryVoltage" Type="String" />
            <asp:Parameter Name="JOnum" Type="String" />
            <asp:Parameter Name="Quoterefnum" Type="String" />
            <asp:Parameter Name="TONP" Type="DateTime" />
            <asp:Parameter Name="ECNREV1" Type="String" />
            <asp:Parameter Name="ECNREV2" Type="String" />
            <asp:Parameter Name="ECNREV3" Type="String" />
            <asp:Parameter Name="ECNREV4" Type="String" />
            <asp:Parameter Name="HPU" Type="String" />
            <asp:Parameter Name="Vahle" Type="String" />
            <asp:Parameter Name="GAREVdate5" Type="DateTime" />
            <asp:Parameter Name="GAREVtoCUST5" Type="DateTime" />
            <asp:Parameter Name="GAREVtoSALES5" Type="DateTime" />
            <asp:Parameter Name="ECNREV5" Type="String" />
            <asp:Parameter Name="OSD" Type="DateTime" />
            <asp:Parameter Name="MultiECN" Type="String" />
            <asp:Parameter Name="MultiECNDate" Type="DateTime" />
            <asp:Parameter Name="RA" Type="Boolean" />
            <asp:Parameter Name="TL" Type="Boolean" />
            <asp:Parameter Name="RG" Type="Boolean" />
            <asp:Parameter Name="LT" Type="Boolean" />
            <asp:Parameter Name="BR" Type="Boolean" />
            <asp:Parameter Name="JW" Type="Boolean" />
            <asp:Parameter Name="BW" Type="Boolean" />
            <asp:Parameter Name="HC" Type="Boolean" />
            <asp:Parameter Name="JR" Type="Boolean" />
            <asp:Parameter Name="LW" Type="Boolean" />
            <asp:Parameter Name="RC" Type="Boolean" />
            <asp:Parameter Name="JT" Type="Boolean" />
            <asp:Parameter Name="ECN1" Type="String" />
            <asp:Parameter Name="ECN2" Type="String" />
            <asp:Parameter Name="ECN3" Type="String" />
            <asp:Parameter Name="ECN4" Type="String" />
            <asp:Parameter Name="ECN5" Type="String" />
            <asp:Parameter Name="ECN6" Type="String" />
            <asp:Parameter Name="ECNDate1" Type="DateTime" />
            <asp:Parameter Name="ECNDate2" Type="DateTime" />
            <asp:Parameter Name="ECNDate3" Type="DateTime" />
            <asp:Parameter Name="ECNDate4" Type="DateTime" />
            <asp:Parameter Name="ECNDate5" Type="DateTime" />
            <asp:Parameter Name="ECNDate6" Type="DateTime" />
            <asp:Parameter Name="ECN1Text" Type="String" />
            <asp:Parameter Name="ECN2Text" Type="String" />
            <asp:Parameter Name="ECN3Text" Type="String" />
            <asp:Parameter Name="ECN4Text" Type="String" />
            <asp:Parameter Name="ECN5Text" Type="String" />
            <asp:Parameter Name="ECN6Text" Type="String" />
            <asp:Parameter Name="GAESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="ELESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="TAESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="ELREQD" Type="Boolean" />
            <asp:Parameter Name="OrdernotesESR" Type="String" />
            <asp:Parameter Name="SYSPROPESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="HYESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="PNESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="INSTALLESTRELDATE" Type="DateTime" />
            <asp:Parameter Name="SOnum" Type="String" />
            <asp:Parameter Name="RW" Type="Boolean" />
            <asp:Parameter Name="LabelType" Type="String" />
            <asp:Parameter Name="LabelDateComp" Type="DateTime" />
            <asp:Parameter Name="LabelDateSent" Type="DateTime" />
            <asp:Parameter Name="LabelMethod" Type="String" />
            <asp:Parameter Name="LabelRecvd" Type="DateTime" />
            <asp:Parameter Name="LabelRecvdBy" Type="String" />
            <asp:Parameter Name="ECNDate7" Type="String" />
            <asp:Parameter Name="ECN7" Type="String" />
            <asp:Parameter Name="ECN7Text" Type="String" />
            <asp:Parameter Name="ECNDate8" Type="String" />
            <asp:Parameter Name="ECN8" Type="String" />
            <asp:Parameter Name="ECN8Text" Type="String" />
            <asp:Parameter Name="Drafter7" Type="String" />
            <asp:Parameter Name="lead_setter" Type="String" />
            <asp:Parameter Name="WW" Type="Boolean" />
            <asp:Parameter Name="manMOD" Type="String" />
            <asp:Parameter Name="Date_to_Check" Type="DateTime" />
            <asp:Parameter Name="Job_Date_Check_Complete" Type="DateTime" />
            <asp:Parameter Name="Job_Date_to_BOM" Type="DateTime" />
            <asp:Parameter Name="Job_Date_Rel_To_Plan" Type="DateTime" />
            <asp:Parameter Name="control_est_rel_date" Type="DateTime" />
            <asp:Parameter Name="control_comp_date" Type="DateTime" />
            <asp:Parameter Name="control_to_plan_date" Type="DateTime" />
            <asp:Parameter Name="Item_category" Type="String" />
            <asp:Parameter Name="LeadTime" Type="String" />
            <asp:Parameter Name="ECNDate9" Type="String" />
            <asp:Parameter Name="ECN9" Type="String" />
            <asp:Parameter Name="ECN9Text" Type="String" />
            <asp:Parameter Name="ECNDate10" Type="String" />
            <asp:Parameter Name="ECN10" Type="String" />
            <asp:Parameter Name="ECN10Text" Type="String" />
            <asp:Parameter Name="ECNDate11" Type="String" />
            <asp:Parameter Name="ECN11" Type="String" />
            <asp:Parameter Name="ECN11Text" Type="String" />
            <asp:Parameter Name="ECNDate12" Type="String" />
            <asp:Parameter Name="ECN12" Type="String" />
            <asp:Parameter Name="ECN12Text" Type="String" />
            <asp:Parameter Name="Labels_Reqd" Type="Boolean" />
            <asp:Parameter DbType="Time" Name="TimeCreated" />
            <asp:Parameter Name="DateCreated" Type="DateTime" />
            <asp:Parameter Name="Label_ID" Type="Int32" />
            <asp:Parameter Name="Date_Modified" Type="DateTime" />
            <asp:Parameter Name="MECHNotes" Type="String" />
            <asp:Parameter Name="CONTROLNotes" Type="String" />
            <asp:Parameter Name="Original_ID" Type="Int32" />
        </UpdateParameters>
    </asp:ObjectDataSource>
</asp:Content>
